### PR TITLE
Fixed left foot shadow break on ungroup

### PR DESCRIPTION
**Pull request by ifohancroft**
When ungrouping the left foot, two of the shadows were breaking. This PR fixes this.

This pull request also includes the changes made in my previous one (#6) so I can submit multiple fixes without waiting for each to be merged before submitting the next one or leaving you having to resolve merge conflicts.

### CODE REVIEW

**Comment by ifohancroft** [comment]
Just a reminder to check the PR :D

**Comment by garrett** [comment]
I noticed that some things subtle change between standard grouped version of Tux and the ungrouped one. To identify the problem areas, I did a visual diff by merging an export of the grouped (standard) and ungrouped version of Tux, and then inverted the image for making it easier to look at:

tux-diff

Here's another one with the values auto-leveled (and hue inverted after, to get the original hue), to better highlight the problem areas:

tux-diff-levels

(But as a lot of this doesn't show up in the original diff, the problem areas are probably not noticable enough to care in this second one. The first one shows that there are definitely some issues — especially with the eye on the left and the head area next to the eye.)

**Comment by ifohancroft** [comment]
This is interesting. I have played with every single path of Tux but I haven't done such inspection. Comparing it just visually, by watching the original ungrouped Tux with the grouped one, there were only two areas that make a noticable difference (and it is a significant one), one were the shadows on the right leg, that was fixed by merging PR #4 and the other (the only one currently left to be fixed) is the left leg's shadows, which this PR fixes.

There are a thing or two more I'd like to fix in Tux (some parts sticking out that shouldn't be and a couple of sharps points in the curves, with them being smaller ones - maybe I should create a single PR fixing them all at once?) but regarding problems happening in the ungrouping, I agree that the rest aren't really worth it as they are not noticable and the only significant ones are this one and the one already fixed.

**Comment by garrett** [comment]
Here's what I did:
1. Export the SVG as-is from Inkscape as a PNG
2. Ungroup Tux
3. Export again as another PNG
4. Open both PNGs in GIMP
5. Copy one PNG to the other, creating a layer (double click on the floating selection to make it a layer)
6. Select "difference" as the mode for the top layer
7. Flatten image
8. Select "Colors → Invert" from the menu
9. Export as a different PNG
10. Optionally use Levels (Menu: Colors → Levels)

If you'd like to clean up the paths some more, that would be welcome. Thanks!

**Comment by ifohancroft** [comment]
Thank you very much!
I totally forgot about the difference layer blending mode in GIMP. This is what was confusing me mainly.

Awesome! Thank you too!
I'll start right away after this PR gets merged (trying to avoid merge conflicts and gotta admit I am still getting used to, to some of git's features/workflows).

During my quick tests of cleaning up the paths I have noticed some nodes changing so I will take my time with this one, as to avoid unneccessary changes in the path curves, to make sure I only change what needs fixing/cleaning up, so the PR for that (I think it would be just one containing the cleaned up things together and last one as I don't really see anything else that can be/should be or needs to be fixed) would probably be coming in a couple of weeks.

**Comment by garrett** [comment]
As this PR fixes the left foot shadow break when ungrouping, I'll merge it in.

Hopefully we can get it to the point where Sticker Mule accepts it for stickers. I know a lot of people in the community use them for various projects, so having this Tux SVG supported would be a great thing.

Thanks again! We'll need to update the README noting your contributions too. :wink:

**Comment by ifohancroft** [comment]
> As this PR fixes the left foot shadow break when ungrouping, I'll merge it in.
> 
> Hopefully we can get it to the point where Sticker Mule accepts it for stickers. I know a lot of people in the community use them for various projects, so having this Tux SVG supported would be a great thing.
> 
> Thanks again! We'll need to update the README noting your contributions too. wink

Awesome!

They currently accept it for stickers but unfortunately, not for full bleed.
When done with the cleanup, I'll contact them to see if this is enough. If not and they suggest changes that make it printable as full bleed, I'll open an RFC Issue about the topic. If the changes suggessted aren't just a couple of tiny details in the outline, maybe we can have separate version that's suitable for full bleed stickers.

Most welcome and thank you for that! Feel free to update the README yourself as I have no idea what to put :D

**Pull request merged**
