### PR TITLE
Add sticker and cutline

### LINKED ISSUE #10: Create a sticker variant with "bleed"
StickerMule needs a version of Tux that's optimized for sticker usage. This requires color bleed off the edges so when the Tux sticker is cut, the color will bump right up to the edges.

Quoting @ifohancroft from https://github.com/garrett/Tux/pull/8#issuecomment-621994491:
> To be able to print designs in full bleed, their outer edges need to have 1/8th inch of flat color.

Example:
W3UR5EP

And from https://github.com/garrett/Tux/pull/8#issuecomment-624190623, here's an example PDF of what's needed too: [tux-full-bleed.pdf](https://github.com/garrett/Tux/files/4635611/tux-full-bleed.pdf)

### PR DESCRIPTION
**Pull request by garrett**
Adds a sticker; fixes #10.

### CODE REVIEW

**Comment by garrett** [comment]
@ifohancroft, please let me know what you think about this branch. Does this work for StickerMule?

If it's good, we can merge. Otherwise, I'm happy to make some changes.

**Comment by garrett** [comment]
(Previews are in issue #10 and in the branch itself.)

**Comment by garrett** [comment]
The sticker SVG has a cutline, toggled off by default. I've also made a separate SVG with _just_ the cutline at the same document size.

**Comment by ifohancroft** [comment]
Unfortunately, it doesn't work. Sorry, perhaps I explained it badly. Check my comment on Issue#10

**Comment by ifohancroft** [comment]
I think we can close this PR as well now.

**Pull request closed without merging**
