### PR TITLE
Fixed right leg shadow breaking on ungroup (Fixes Issue #4)

### PR DESCRIPTION
**Pull request by ifohancroft**
It seems that after being created in Inkscape, the file has been edited in other software, then in Inkscape again, without first removing Inkscape specific data, so Inkscape rebuilds the value for the 'd' attribute of the 'path' element from the data it has stored itself (inkscape:original-d), which causes the problem with the leg shadow when ungrouping it.

Deleting the inkscape:original-d attribute along with its value, for the path of the leg shadow, fixes the issue.

Ideally, all inkscape:original-d attributes in the SVG should be removed.

Fixes Issue #4

### CODE REVIEW

**Comment by ifohancroft** [comment]
Just wondering if you have had a chance to go over the changes in this PR?

**Comment by garrett** [comment]
Thanks for the fix! I haven't gone over it yet, but I should ASAP. Past few weeks have been a bit wild.

**Comment by garrett** [comment]
Sorry for the delay! Thanks for pinging me about this!

**Comment by garrett** [comment]
BTW: I did run it through `svgo` to reduce the file size. That's the software other than Inkscape. :wink:

- https://github.com/svg/svgo
- https://jakearchibald.github.io/svgomg/

**Comment by ifohancroft** [comment]
Most welcome! Thank you too!
I have found a problem or two more that I have also managed to find fixes for, will submit them in the next couple of days, but trying to do it one thing at a time to follow git's philosophy.

**Pull request merged**
